# Setup
title:               'Meggs' Musings'
tagline:             'Notes to self about software development'
description:         ''
url:                 "https://cmeggs0.github.io"
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chris Meggs
  email:             meggsc91@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
